# The location of a snapshot can be provided as a file or url. Stack assumes
# a snapshot provided as a file might change, whereas a url resource does not.
#
resolver: lts-21.25
system-ghc: true
#
# packages:
# - some-directory
# - https://example.com/foo/bar/baz-0.0.2.tar.gz
#   subdirs:
#   - auto-update
#   - wai
# Dependency packages to be pulled from upstream that are not in the resolver.
# These entries can reference officially published versions as well as
# forks / in-progress versions pinned to a git hash. For example:
#
extra-deps:
# - 'hakyll-4.15.1.1'
- git: https://github.com/flolac-tw/hakyll.git
  commit: 00e343f385671e966ab10c670859562d634fa593
- 'hakyll-sass-0.2.4'

ghc-options:
  hlibsass: -optc -Wno-error=int-conversion
