yearly_theme: ocean
year: "2020"
organizer:
  - 柯向上
ta_boss: 賴廷彥
ta:
  - name: 林子期 
  - name: 潘廣霖 
  - name: 江宗儒 
  - name: 林敬文 
  - name: 鄭淳丰 
  - name: 潘昱仁 
  - name: 曾守瑜 
  - name: 張耀晟 

test: test
