name: Hakyll site CI

on:
  push:
    branches:
      - master
  schedule:
    # Run every day at 20:00.
    - cron: '0 20 * * *'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc: [ '8.8.3' ]
    env:
      FLAGS: "--flag hakyll:-previewServer --flag hakyll:-watchServer --flag hakyll:-checkexternal"

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: ${{ matrix.ghc }}
        stack-version: 'latest'
    - name: Cache ~/.stack
      uses: actions/cache@v1
      with:
        path: ~/.stack
        key: cabal-store-${{ runner.OS }}-${{ hashFiles('stack.yaml') }}
        restore-keys: |
          cabal-store-${{ runner.OS }}-
    - name: Cache .stack-work
      uses: actions/cache@v1
      with:
        path: .stack-work
        key: stack-work-${{ runner.OS }}-${{ hashFiles('stack.yaml') }}
        restore-keys: |
          stack-work-${{ runner.OS }}-
    - name: Build dependencies and the site generator
      run: |
        stack build ${FLAGS}
    - name: Build the site
      env:
        # citeproc requires the locale environment variable.
        LANG: en_US.UTF-8
      run: |
        stack build ${FLAGS} --exec "site build"
    - name: Check the site output
      run: |
        stack build ${FLAGS} --exec "site check --internal-links"
        
    - uses: peaceiris/actions-gh-pages@v3
      name: Publish to the organsiation site      
      if: github.ref == 'refs/heads/master'
      with:
        # Type the following in the terminal to get private/public keys:
        #
        # ssh-keygen -t rsa -b 4096 -C "$(git config user.email)" -f gh-pages -N ""
        #
        # and add
        #
        #   1. the private key as a secrete ACTIONS_DEPLOY_KEY in the GitHub repo hosting the source code,
        #   2. the public key as a deploy key in the GitHub repo hosting the website.
        #
        # For details, see
        # https://github.com/marketplace/actions/github-pages-action
        #
        deploy_key: ${{ secrets.ACTION_DEPLOY_KEY_TO_TEAM_SITE }}

        # Ensure to match the source branch specified on the GitHub setting.
        #
        external_repository: flolac-tw/flolac-tw.github.io
        publish_branch: master
        publish_dir: _site

        
    - uses: peaceiris/actions-gh-pages@v3
      name: Publish to the project site
      if: github.ref == 'refs/heads/dev'
      with:
        # For details, see
        # https://github.com/marketplace/actions/github-pages-action
        #
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}

        # Ensure to match the source branch specified on the GitHub setting.
        #
        publish_dir: _site
